### ISSUE TITLE
Error getting issuances / List Index out of Range and Retry Timeout 

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/btc_stamps#330]
This may be partially related to the CP issue 
https://github.com/CounterpartyXCP/counterparty-core/issues/1952

fixed here (not currently in a release)
https://github.com/CounterpartyXCP/counterparty-core/commit/5852ef52b5d0ab59670e234c89cc508ea8a5fd98

In either case the retry timeout logic needs to be modified to step up the wait times.

```
Fetching CP Trx [835000..836000]:  98%|█████████▊| 975/1000 [01:52<00:00, 98.82it/s]Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
indexer_1  | Error getting issuances: Expecting value: line 1 column 1 (char 0)
indexer_1  |  Sleeping to retry...
Fetching CP Trx [835000..836000]: 1001it [03:32,  4.70it/s]
indexer_1  | None
indexer_1  | None
indexer_1  | None
indexer_1  | None
indexer_1  | None
indexer_1  | None
indexer_1  | None
indexer_1  | None
indexer_1  | None
indexer_1  | None
```

also appears very related to:

```
Unhandled Exception
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/btc_stamps/indexer/start.py", line 15, in main
    server.start_all(db)
  File "/home/ubuntu/btc_stamps/indexer/src/index_core/server.py", line 351, in start_all
    blocks.follow(db)
  File "/home/ubuntu/btc_stamps/indexer/src/index_core/blocks.py", line 783, in follow
    stamp_issuances_list = fetch_cp_concurrent(block_index, block_tip, indicator=indicator)
  File "/home/ubuntu/btc_stamps/indexer/src/index_core/xcprequest.py", line 54, in fetch_cp_concurrent
    result = future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/btc_stamps/indexer/src/index_core/xcprequest.py", line 154, in get_xcp_block_data
    parsed_block_data = _parse_issuances_from_block(block_data=block_data_from_xcp)
  File "/home/ubuntu/btc_stamps/indexer/src/index_core/xcprequest.py", line 161, in _parse_issuances_from_block
    block_data = json.loads(json.dumps(block_data[0]))
IndexError: list index out of range
```

**Comment by reinamora137** [comment]
changed BACKEND_POLL_INTERVAL to 1s and pushed in v1.8.6
