### ISSUE TITLE
Branch `bitname/testnet` `IndexError: list index out of range`

### ISSUE THREAD

**Issue by btcopenstamp** [stampchain-io/btc_stamps#359]
**Describe the bug**
An error occurred while using the `mint` operation to mint multiple items.

**Branch/Release/Commit Hash of Problem**
Branch `bitname/testnet`.

**To Reproduce**
1. Using the `mint` operation to mint multiple items

**Expected behavior**
The program can run normally and process data.

**Screenshots**

```
Error in minting operations: list index out of range
Traceback (most recent call last):
  File "/Code/btc_stamps/indexer/src/index_core/src101.py", line 355, in handle_mint
    self.src101_dict["tokenid"][index],
IndexError: list index out of range
python-BaseException
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2252, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 2234, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1544, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Code/btc_stamps/indexer/start.py", line 19, in <module>
    main()
  File "/Code/btc_stamps/indexer/start.py", line 15, in main
    server.start_all(db)
  File "/Code/btc_stamps/indexer/src/index_core/server.py", line 359, in start_all
    blocks.follow(db)
  File "/Code/btc_stamps/indexer/src/index_core/blocks.py", line 934, in follow
    block_processor.process_transaction_results(tx_results)
  File "/Code/btc_stamps/indexer/src/index_core/blocks.py", line 127, in process_transaction_results
    _, src101_dict = parse_src101(self.db, prevalidated_src, self.processed_src101_in_block)
  File "/Code/btc_stamps/indexer/src/index_core/src101.py", line 597, in parse_src101
    processor.process()
  File "/Code/btc_stamps/indexer/src/index_core/src101.py", line 592, in process
    self.validate_and_process_operation()
  File "/Code/btc_stamps/indexer/src/index_core/src101.py", line 571, in validate_and_process_operation
    self.handle_mint()
  File "/Code/btc_stamps/indexer/src/index_core/src101.py", line 355, in handle_mint
    self.src101_dict["tokenid"][index],
IndexError: list index out of range
python-BaseException
```

**Additional context**

https://github.com/stampchain-io/btc_stamps/blob/bitname/testnet/indexer/src/index_core/src101.py#L350-L366

The error occurred because deleting array elements while iterating through the array caused an `IndexError`.

**Comment by vikkkko** [comment]
Submitted  https://github.com/stampchain-io/btc_stamps/pull/373 to resolve this error

**Comment by reinamora137** [comment]
fix merged
